language: python
dist: xenial
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
python:
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
  # - osx  # not supported yet
env:
  global:
    - BACKEND_CLIENT_CLOUD_TEST=1  # use beta server for integration tests

# test stage
install:
  - pip install -U --upgrade-strategy=eager pip setuptools
  - pip install -U --upgrade-strategy=eager -r requirements-ci.txt
script:
  - python -m flake8 ai/backend tests
  - python -m pytest --cov=ai.backend.client -v -m "not integration"
after_success:
  - codecov

# other stages
jobs:
  fast_finish: true
  include:
    - stage: deploy
      python: "3.6"
      install: skip
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: "@token"
        password:
          secure: "1guzkX9nbpdMnIB1CgeyjT3izX90TbcdzzKy5opV8WYfEf+mJbGUluoNLr4Mf8h8zjWC+5wwCrgA/uB7qpXI6UH742BVKIqC77LJiFmvDCYsl9vz6YCJ0JEK0h+7K0u5En6TyCuSXAz6IuFfQI2cdEE0O4El3a1E3zQtd95JItspBxlgfP9BSb6qO8C1CvmTpw+9svSB5dZRKrqsH23RCcyeY8UgDRQQpFq1RnKGG/dI+wXfo0DWwcZlXAguSH65VQECVut42kXE6XgedMl44u89LQS4FQHCOBNn/g2tANXyZhjp4n5ROiutYUDBM+IHt933fGz3RGdK3UZef7we3bMWwr9l0dXNz0aVUxVkQWuRUsrspwGDwTC8uNxLvVGv7DZLjwwPIkTVmzSPgo0qock8/j5eqPo8SQXUhrnKG/NBRk17T3z3V4+VZP5VtCPsxILD5a3LN7cXCDiklKtu/s7kOUnVFJd2Liyl0atUIqHkf0+HyeVhjUuQ7lNF3NOyvcwxOovXdsP81NWVieQ98oolZURWc24fJ88SBEMDv6Ti3+xZigGa6kE0HxPoMj2ELBs2cwpVjAxyBmSsNfwQHyfrY9QVbe+HzziGpyG6KL0EPBfwZ5BV8k+hQ8RJp+qmZmEplt2Mcc4NbbBvNOZtqqURx417IXQqwZs3Aiwv4Ig="

notifications:
  webhooks:
    secure: "u7Ylvc6HV9HUTS5e4E+BHeIJLMmR4EBH0mk45psBGBZn81TAmcJ65Xzcus9vGO3HZalBNzIq8YxJJJk6Dan9YY5wBnxsdwTbh8+dcS/9UFLbkc5Erh4C9B/4gPVd5HxfQc2hDBIfQUup5kWiSJlTgxGO0QDDspSoeBQYmIYJkfa7Sb6UQc3t6KHi1j9Hn5h1ycqsHOnPrPrG6u0EqwUvBuk+rGdZYGeilgwK5MrlhHmnB9vn60EQZr0mesYBDEXnF4+sVXswY+0AV+PYBcZkxwFNl3mZ2IyMMp6/YIwogLtzGwlS2XTXnTRgrjj7oPDLOBQnwv4BzQ0HJGbbNocl5K+cy1GmxOFOm0XNxiK3T3hbZIl5OY7Sger9JNgBM61Lx5tfW6S9r3bHyzx1ZsUgEJyYwGRl0KYTP3qI1blgyJlU7qvXensTFSRtTJq3PD+ri8o6GjRseEqZWIw5IkqR6FfFpATEOAqoOS/6925YQ5nSFHoLYq+tB6XhY20+p5cJKY9ZrPSsMR5OK5yrchmm/z0e3lpw7i94oA9qcW4M6qvWW45syNtnB9qa88pqR/j03CDv0eAFp1fzcPd4z4YZKUX43V0ziLl0ybcORkEHujwSO4xMckMC6gG7vqFV/2rS+Mq+kaD4GCtMajiC0DDal14jqpJFBKHp0nEEvC+vtQc="
