language: python
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
python:
  - "3.5"
  - "3.6"
os:
  - linux
  # - osx  # not supported yet

# test stage
install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt
script:
  - python -m flake8 ai/backend tests
  - python -m pytest --cov=ai.backend.client -v -m "not integration"
after_success:
  - codecov

# other stages
jobs:
  fast_finish: true
  include:
    - stage: deploy
      python: "3.6"
      install: skip
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        user: lablup
        password:
          secure: "n7JU0VbEr0ibhUo5zXOk7t59/T9lkAl7ypnZII4c2j9uvfVu3SGYlLf8Ekj1+8TA8Wdnknq7ZIo/zSZzfT6JMmI1KMyhPdk4IorDkA/BrLDm1crIln4IMbxC/gzH41wiG9583IuWohOD5yEmxGkRGh4CPlWwuFKmpQiWm0uXqpnf/x5nKNNVaY2M6R+MBvd+8Xb/zcEvcQIsF7E3vBof/PPSvAiRn5gZMOB7kMf+T8VlYOb3C57hJ1hGCk1PEO72t7vtkHezmigZTSZfWIC3L7fp6QPrUvPQMVDgMpw9vpHtC8hRqvg4pfPcb4XANZNCAqG7+HdOVTGnTOmwWk0SvYKGJfV0spDWLcjCPUrudAM8VR+fjJFEX3JzkxixcrwPYNuTpG8vw/DK9vfcSOjNXdR91nWHPYIZ3gfkeTRBx8SaRzWOZ//hRO3MGsD8pjXjdgk0EgFkHTgPuhXAz1knTW3r5q60ysr87Zy0n1S2W5eS95GW0rVdgU+XlxAyuXwEa+5o/5pNROOTlGTrrX/bcSitRc3o3KPkvmwZmTFZNIeqMHYM9VGMCj9lwheDfBOqfZrWg7WMh7Lg/Mbus+RXpvkTn+Ku3yGaeEpLWFf1Xt2L9pmSp/4dAABArq5t9oROAERwWodW7PIz3qox/1qEyk8ZY8gwWbWHHhKaT2Zd3PY="
        skip_upload_docs: true

notifications:
  webhooks:
    secure: "u7Ylvc6HV9HUTS5e4E+BHeIJLMmR4EBH0mk45psBGBZn81TAmcJ65Xzcus9vGO3HZalBNzIq8YxJJJk6Dan9YY5wBnxsdwTbh8+dcS/9UFLbkc5Erh4C9B/4gPVd5HxfQc2hDBIfQUup5kWiSJlTgxGO0QDDspSoeBQYmIYJkfa7Sb6UQc3t6KHi1j9Hn5h1ycqsHOnPrPrG6u0EqwUvBuk+rGdZYGeilgwK5MrlhHmnB9vn60EQZr0mesYBDEXnF4+sVXswY+0AV+PYBcZkxwFNl3mZ2IyMMp6/YIwogLtzGwlS2XTXnTRgrjj7oPDLOBQnwv4BzQ0HJGbbNocl5K+cy1GmxOFOm0XNxiK3T3hbZIl5OY7Sger9JNgBM61Lx5tfW6S9r3bHyzx1ZsUgEJyYwGRl0KYTP3qI1blgyJlU7qvXensTFSRtTJq3PD+ri8o6GjRseEqZWIw5IkqR6FfFpATEOAqoOS/6925YQ5nSFHoLYq+tB6XhY20+p5cJKY9ZrPSsMR5OK5yrchmm/z0e3lpw7i94oA9qcW4M6qvWW45syNtnB9qa88pqR/j03CDv0eAFp1fzcPd4z4YZKUX43V0ziLl0ybcORkEHujwSO4xMckMC6gG7vqFV/2rS+Mq+kaD4GCtMajiC0DDal14jqpJFBKHp0nEEvC+vtQc="
