language: python
dist: xenial
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
python:
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
  # - osx  # not supported yet
env:
  global:
    - BACKEND_CLIENT_CLOUD_TEST=1  # use beta server for integration tests

# test stage
install:
  - pip install -U --upgrade-strategy=eager pip setuptools
  - pip install -U --upgrade-strategy=eager -r requirements-ci.txt
script:
  - python -m flake8 ai/backend tests
  - python -m pytest --cov=ai.backend.client -v -m "not integration"
after_success:
  - codecov

# other stages
jobs:
  fast_finish: true
  include:
    - stage: deploy
      python: "3.6"
      install: skip
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        user: @token
        password:
          secure: "gUNrQf0RJwD+EozXFh0DPgXUeFDTLQB3ewKHq4y1dBBePQ4XjE5qInyP5EfZHBze1pHBzK2tsgh2E6hlv9KPxGgvk3h1lz/TjwedKgChmJnp9AFXt8X3gXR43OFPxZBPltpK+jCHf5/iKuWO1ziLUhENANkaUwDUZTQvQdOp8sJz1aqIuJKohp36BikgiGMT9nS8lcZulKh90F4K51j3vsE3/hYlfeY9e/v9SFDwDnwMeFN+uD5ljxAZpk68lux6Q91ufbCdijZsXBxIM353zl8Ke0vFTzertCNiDAJH8e17zFfTu++XPUJLsWpkCS4/1MwF3zOZ2BIalAnan+fbYJo4ZokynWGoFEXlNc3BtYsJ4PGCAyWA+MT0f3Ll5mX5hRtY9YqiLf3ZumvjOy3pl0i+2FiGqXQoUcByhYVwgkmS9AHpcNsWo0ApNU+KRNApX8VQ0ysYNGq9NqDz6GFVfDn//e0l1PsBXbFIP1FE11dRMcoMWg48SZHLp4MDWgABevrU9/61FuOgaP78MCZhp/FEeBiwRWUDhs6CUm2KWKPjSDawbLNzp36FfeLQtczN2JQ0b4oO+AOz1ORUVBVKV2duouUCZHcc5k1yXbtPVvu3bhvJL8MwD9NEa2qkUs6fSt2sID+ro9ZW1ssWhi9Q5ZAiup3a8/eWje4nkImC1kU="
        skip_upload_docs: true

notifications:
  webhooks:
    secure: "u7Ylvc6HV9HUTS5e4E+BHeIJLMmR4EBH0mk45psBGBZn81TAmcJ65Xzcus9vGO3HZalBNzIq8YxJJJk6Dan9YY5wBnxsdwTbh8+dcS/9UFLbkc5Erh4C9B/4gPVd5HxfQc2hDBIfQUup5kWiSJlTgxGO0QDDspSoeBQYmIYJkfa7Sb6UQc3t6KHi1j9Hn5h1ycqsHOnPrPrG6u0EqwUvBuk+rGdZYGeilgwK5MrlhHmnB9vn60EQZr0mesYBDEXnF4+sVXswY+0AV+PYBcZkxwFNl3mZ2IyMMp6/YIwogLtzGwlS2XTXnTRgrjj7oPDLOBQnwv4BzQ0HJGbbNocl5K+cy1GmxOFOm0XNxiK3T3hbZIl5OY7Sger9JNgBM61Lx5tfW6S9r3bHyzx1ZsUgEJyYwGRl0KYTP3qI1blgyJlU7qvXensTFSRtTJq3PD+ri8o6GjRseEqZWIw5IkqR6FfFpATEOAqoOS/6925YQ5nSFHoLYq+tB6XhY20+p5cJKY9ZrPSsMR5OK5yrchmm/z0e3lpw7i94oA9qcW4M6qvWW45syNtnB9qa88pqR/j03CDv0eAFp1fzcPd4z4YZKUX43V0ziLl0ybcORkEHujwSO4xMckMC6gG7vqFV/2rS+Mq+kaD4GCtMajiC0DDal14jqpJFBKHp0nEEvC+vtQc="
